// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sshunoitrbfjwjxvxtbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzaHVub2l0cmJmandqeHZ4dGJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NzA3MTIsImV4cCI6MjA2MTQ0NjcxMn0.FDDtCEWN_UQIzbt8ejyj27XNM-zd45g4Pagj0_e4Ko4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);