
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sshunoitrbfjwjxvxtbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzaHVub2l0cmJmandqeHZ4dGJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTQ5MjAxMzEsImV4cCI6MjAzMDQ5NjEzMX0.HQihwCznFm4Hje94CMe_ekrA-YEgU1VeL7wi5V9L74s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
