
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getEnvVar } from '@/lib/utils';

const SUPABASE_URL = getEnvVar("SUPABASE_URL") // "https://sshunoitrbfjwjxvxtbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = getEnvVar("SUPABASE_PUBLISHABLE_KEY") // "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzaHVub2l0cmJmandqeHZ4dGJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NzcwMjAsImV4cCI6MjA2MTQ1MzAyMH0.GIii2mkPn_Q2fP1qIB1stn7tYbGKVndPgIAu_kr_-qc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);


export const supabseSellerListeListener = supabase.channel('table:sellers');
