name: Deploy to Truehost via FTP

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Step - Checkout Code
        run: echo "Checking out repository..."
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Echo Step - Set up Bun
        run: echo "Installing Bun..."
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Echo Step - Install dependencies
        run: echo "Installing dependencies with --legacy-peer-deps..."
      - name: Install dependencies
        run: bun install --legacy-peer-deps

      - name: Echo Step - Build Project
        run: echo "Building project with Bun..."
      - name: Build
        run: bun run build

      - name: Echo Step - Deploy via FTP
        run: echo "Uploading dist/ folder to /public_html/deployments (clean slate)..."
      - name: FTP Deploy (Clean Slate)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/
          server-dir: /dev.meetnmart.com/
          #dangerous-clean-slate: true

      - name: Echo Step - Deployment Finished
        run: echo "Deployment completed successfully!"
