name: Deploy to Truehost via SFTP

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Step - Checkout Code
        run: echo "Checking out repository..."
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Echo Step - Set up Bun
        run: echo "Installing Bun..."
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Echo Step - Install dependencies
        run: echo "Installing dependencies with --legacy-peer-deps..."
      - name: Install dependencies
        run: bun install --legacy-peer-deps

      - name: Echo Step - Build Project
        run: echo "Building project with Bun..."
      - name: Build
        run: bun run build

      - name: Echo Step - Upload via SFTP
        run: echo "Uploading dist/ folder via SFTP to /public_html/deployments..."
      - name: SFTP Deploy
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          source: "dist/*"
          target: "/public_html/deployments"
          rm: true

      - name: Echo Step - Deployment Finished
        run: echo "Deployment via SFTP completed successfully!"
